### ISSUE TITLE
Can not pod install when project tartget 9.3

### ISSUE THREAD

**Issue by veila** [witekbobrowski/EPUBKit#4]

**Comment by witekbobrowski** [comment]
Hi! Thank you for trying out my library :) 

I am happy to say that the issue should no longer occure, I have not even notice that there was dated version of the library pushed to cocoapods…

Now after update to Swift 4.2 and lowering the project target to iOS 9.3 you should be good to go!

Please close this issue if you no longer have this problem.

**Comment by veila** [comment]
Hi! Thanks you so much
I want to report new issue. That is EPubKit does not extract some file epub, maybe because the version of file epub, 2.0 or 3.0, or some epub files have sub chapter.
How can I send you epub file that I can not extract?

**Comment by witekbobrowski** [comment]
I the initial problem was resolved, please let me close it. Could you open another one with some code and error messages you are getting. You could use `EPUBParserDelegate` to get details on which step the parsing fails. I have email address on my profile so feel free to send the epub there with issue title as subject. Thanks!
